plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    id 'maven-publish'
    id 'org.jetbrains.kotlin.jvm' version "${kotlin_version}"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "chat-remastered" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

// Гарантируем что Kotlin-классы клиента скомпилированы до Java-миксинов
tasks.named("compileClientJava") {
    dependsOn tasks.named("compileClientKotlin")
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

kotlin {
    jvmToolchain(21)
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName}" }
    }
}
