org.gradle.jvmargs=-Xmx5G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.11
loader_version=0.18.6
loom_version=1.14-SNAPSHOT

mod_version=0.2.0
maven_group=dev.errnicraft
archives_base_name=chat-remastered

fabric_version=0.139.4+1.21.11
cloth_version=21.11.153
