plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    id 'maven-publish'
}

def loaderTag = 'fabric'
def mcVersion = project.minecraft_version

version = "${rootProject.mod_version}+${mcVersion}"
group = rootProject.maven_group

base {
    archivesName = "${rootProject.archives_base_name}-${loaderTag}"
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "chat-remastered" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

repositories {
    maven { url "https://maven.shedaniel.me/" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    modImplementation("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }
}

processResources {
    inputs.property "version", project.version
    inputs.property "protocol_version", rootProject.protocol_version
    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version,
                "protocol_version": inputs.properties.protocol_version
    }
}

jar {
    archiveVersion = "${rootProject.mod_version}+${mcVersion}"

    from("${rootDir}/LICENSE") {
        rename { "${it}_${project.base.archivesName}" }
    }
}
